config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "plants#home"

  get "user_root", to: redirect("/plants"), as: :user_root

  #Route to the about page
  get "/about", to: "about#index"

  get "/plants/search", to: "plants#search"
  resources :plants
  get "/plants/:id/buy", to: "plants#buy", as: :buy_plant

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  belongs_to :buyer, class_name: "User", optional: true
  has_one_attached :image

  # Used to filter plants
  scope :filter_by_name, ->(name) { where("lower(name) like ?", "%#{name.downcase}%") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plants
  has_many :bought_plants, class_name: "Plant", foreign_key: :buyer_id
  has_one_attached :image
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end;

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @user_created_plants = current_user.plants
    @user_created_plants = @user_created_plants.filter_by_name(params[:query]) if params[:query].present?

    @user_bought_plants = current_user.bought_plants
    @user_bought_plants = @user_bought_plants.filter_by_name(params[:query]) if params[:query].present?

    @collection = Plant.where(nil)
    @collection = @collection.filter_by_name(params[:query]) if params[:query].present?
    @collection = @collection.select { |plant| plant.user_id != current_user.id }
  end

  def search
    p params[:query]
    redirect_to action: "index", query: params[:query]
  end

  def new
    @plant = Plant.new
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def create
    @plant = current_user.plants.build(plant_params)

    if @plant.save
      redirect_to @plant
    else
      p @plant.errors
      render :new
    end
  end

  def buy
    @plant = Plant.find(params[:id])

    @plant.buyer = current_user
    if @plant.save
      redirect_to @plant
    else
      render :index
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])

    if @plant.update(plant_params)
      redirect_to @plant
    else
      render :edit
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to plants_path
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :age, :height_flora, :height_pot, :price, :other_information, :image)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/about/index.html.erb
 <%# About view shown in Nav bar %>

 <h1>About</h1>

 <h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
     Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
     nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
     reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
     pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
     qui officia deserunt mollit anim id est laborum.</h5>

app/views/layouts/_flash.html.erb
 <%# Alert message the user will see when logged in %>
 <br>
 <% flash.each do |name, msg| %>
 <div class="alert alert-warning" role="alert">
     <%= content_tag(:div, msg) %>
 </div>
 <% end %>

app/views/layouts/_footer.html.erb
<br><br><br>

<center> © 2021 BeLeaf </center>

app/views/layouts/_navbar.html.erb
 <%# Navbar implemented with Bootstrap  %>

 <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <div class="container">
         <a class="navbar-brand" href="#">BeLeaf</a>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                 <li class="nav-item">
                     <%# Buttons the user will be able to interact, shown in the Navbar  %>
                     <%= link_to "Home", root_path, class: "nav-link" %>
                 </li>

                 <li class="nav-item">
                     <%= link_to "About", about_path, class: "nav-link" %>
                 </li>

                 <%# Condition used on what the user is able to see once logged in.  %>
                 <% if user_signed_in? %>

                 <li class="nav-item">
                     <%= link_to "Plants", plants_path, class: "nav-link" %>
                 </li>

                 <li class="nav-item">
                     <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
                 </li>

                 <li class="nav-item">
                     <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                 </li>

                 <% else %>
                 <li class="nav-item">
                     <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                 </li>

                 <% end %>


                 </li>

             </ul>

         </div>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
     </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Beleaf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
</head>

<body>
    <%# Using partial to render _navbar  %>
    <%= render "layouts/navbar" %>

    <div class="container">
        <%# Using partial to render _flash  %>
        <%= render "layouts/flash" %>
        <%= yield %>
    </div>

    <%# Using partial to render _footer  %>
    <%= render "layouts/footer" %>

</body>

</html>

app/views/plants/_flora.html.erb
<%# Adding a partial for the list of plants, both user and plants to buy. %>

<div class="container">
    <div class="row row-cols-1 row-cols-md-2 row-cols-xl-4">
        <% plant_list.each do |plant| %>
        <div class="col .col-md-2 gy-5">
            <div class="plant">
                <a href="/plants/<%= plant.id %>" class="nounderline">
                    <%= plant.name %>, <%= plant.age %>
                    <div>
                        <%= image_tag plant.image, class: "image-box" if plant.image.attached? %>
                    </div>
                </a>
                <% if show_buttons %>
                <div class="button-container">
                    <% if !plant.buyer %>
                    <%= button_to "Buy  $#{plant.price}", user_signed_in? ? buy_plant_path(plant) : new_user_session_path, method: :get, class: "btn btn-success" %>

                    <% else %>
                    Out of Stock

                    <% end %>
                </div>
                <% end %>
            </div>
            <div class="square"></div>

        </div>
        <% end %>

    </div>
</div>

app/views/plants/_form.html.erb
<%# Adding a form so that the user can input data %>

<div class="col-md-6 offset-md-3">
    <div class="bg-light p-5 rounded-lg m-3">
        <div class="mb-3">

            <%= form_with model: plant do |form| %>
            <div>
                <%= form.label :name, "Name of flora" %><br />
                <%= form.text_field :name, class: "form-control" %><br />
                <% plant.errors.full_messages_for(:name).each do |message| %>
                <div><%= message %></div>
                <% end %>
            </div>

            <div>
                <%= form.label :age, "Age of flora" %><br />
                <%= form.text_field :age, class: "form-control" %><br />
                <% plant.errors.full_messages_for(:age).each do |message| %>
                <div><%= message %></div>
                <% end %>
            </div>

            <div>
                <%= form.label :height_flora, "Height of flora" %><br />
                <%= form.text_field :height_flora, class: "form-control" %><br />
                <% plant.errors.full_messages_for(:height_flora).each do |message| %>
                <div><%= message %></div>
                <% end %>
            </div>

            <div>
                <%= form.label :height_pot, "Height of pot" %><br />
                <%= form.text_field :height_pot, class: "form-control" %><br />
                <% plant.errors.full_messages_for(:height_pot).each do |message| %>
                <div><%= message %></div>
                <% end %>
            </div>

            <div>
                <%= form.label :price, "Price" %><br />
                <%= form.text_field :price, class: "form-control" %><br />
                <% plant.errors.full_messages_for(:price).each do |message| %>
                <div><%= message %></div>
                <% end %>
            </div>

            <div>
                <%= form.label :other_information, "Other information" %><br />
                <%= form.text_area :other_information, class: "form-control" %><br />
                <% plant.errors.full_messages_for(:other_information).each do |message| %>
                <div><%= message %></div>
                <% end %>
            </div>

            <div class="field">
                <%= form.label :image %>
                <%= form.file_field :image %>
            </div>
            <br>
            <div><%= form.submit "Save", class: "btn btn-success"  %></div>
            <% end %>

        </div>
    </div>
</div>

app/views/plants/_navbar.thml.erb
 <%= link_to "Home", root_path  %> |
  <%= link_to "About", plants_about_path  %>

app/views/plants/about.html.erb
<h1>About</h1> 

<h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa 
qui officia deserunt mollit anim id est laborum.</h5>

app/views/plants/edit.html.erb
<h1>
    <center>Edit Plant<center>
</h1>

<%# Using partial to render _form  %>
<%= render "form", plant: @plant %>

<center><%= link_to "Back", plants_path, class: "btn btn-secondary" %><center>

app/views/plants/home.html.erb
<div class="container">
    <div class="row">
        <div class="col-6">
            <%= image_tag asset_path("image-one.jpeg"), alt: "Website main photo", class: "image-one" %>
        </div>
        <div class="col-6 align-self-center">
            <h1>
                <center>BeLeaf<center>
            </h1>
            <br>
            <center>
                <h5 class="index_main_text">Be part of our exclusive club, and indulge in our private collection of international rare flora.</h5>
                <center>
                    <br>
                    <%# Condition used to redirect the user to the Plants page, once logged in  %>
                    <center><%= button_to "View our collection", user_signed_in? ? plants_path : new_user_session_path, method: :get, class: "btn btn-secondary" %><center>
        </div>
    </div>
</div>

app/views/plants/index.html.erb
<div class="row">
    <div class="col-auto">
        <%= form_with url: plants_search_path, method: :get do |form| %>
        <div class="search-form">
            <%= form.label :query, "Search for:" %>
            <%= form.text_field :query, class: "form-control" %>
            <%= form.submit "Search", class: "btn btn-outline-secondary" %>
        </div>
        <% end %>
    </div>

    <% if params[:query]%>
    <div class="col-auto">
        <%= form_with url: plants_path, method: :get do |form| %>
        <div class="search-form">
            <%= form.submit "Clear search", class: "btn btn-outline-danger" %>
        </div>
        <% end %>
    </div>
    <% end %>
</div>


<br>
<h1>
    <center>My Plants<center><%= button_to "Sell here!", new_plant_path, method: :get, class: "btn btn-secondary" %>
</h1>



<%# Condition used to check if the current_user has added any plants to sell, if so, plants will be displayed, 
if not, they will get a message they dont have plants listed. %>
<%# Please note that current_users will not be able to see their own plants in the Collection as they are selling their plants. 
If they don't want to sell it, they can delete the entry of the plant and keep it. They will be able to see what everyone else has 
poseted to sell.  %>
<% if @user_created_plants.length > 0   %>

<%= render "flora", plant_list: @user_created_plants, show_buttons: false %>
<br><br><br>

<% else %>
<h3 class="heading_sell_text">
    <center>No listing of your plants, yet!<center>
</h3>
<% end %>

<hr>
<h1>
    <center>My Orders<center>
</h1>
<%= render "flora", plant_list: @user_bought_plants, show_buttons: false %>


<br><br><br>
<hr>
<%# Area where users will be able to see the plants available to buy.  %>
<h1>
    <center>Collection<center>
</h1>

<%= render "flora", plant_list: @collection, show_buttons: true %>

app/views/plants/login.html.erb
<br>
<h4><center>Take a look at our newest and valuable acquisitions.<center></h4>

app/views/plants/new.html.erb
<%# "Adding a new entry" view when user wants to sell a plant.  %>
<h1>
    <center>New Plant<center>
</h1>

<%# Using partial to render _form  %>
<%= render "form", plant: @plant %>

<center><%= link_to "Back", plants_path, class: "btn btn-secondary" %><center>

app/views/plants/show.html.erb
<%# "Adding a new entry" view when user wants to sell a plant.  %>

<div class="col-md-6 offset-md-3">
    <div class="bg-light p-5 rounded-lg m-3">
        <div class="mb-3">

            <h3>
                <center>Details of your plant<center>
            </h3>
            <br>
            <label for="plant_name">🌿 Name of flora: <%= @plant.name %></label>
            <br>
            <label for="plant_name">⏳ Age of flora: <%= @plant.age %></label>
            <br>
            <label for="plant_name">🌴 Height of flora: <%= @plant.height_flora %></label>
            <br>
            <label for="plant_name">🪴 Height of pot: <%= @plant.height_pot %></label>
            <br>
            <label for="plant_name">💸 Selling price: <%= @plant.price %></label>
            <br>
            <label for="plant_name">🔍 Other information: <%= @plant.other_information %></label>


            <% if @plant.image.attached?%>
            <center>
                <%= image_tag url_for(@plant.image), class: "plant_view" %>
                <center>
                    <%end%>


                    <%if current_user.id == @plant.user_id %>
                    <br>
                    <div class="button-container">
                        <%= button_to "Edit", edit_plant_path(@plant), class: "btn btn-success", method: :get %>
                        <%= button_to "Destroy", plant_path(@plant), class: "btn btn-danger", 
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
                    </div>
                    <%else%>

                    <%end%>

        </div>
    </div>
</div>
<center><%= link_to "Back", plants_path, class: "btn btn-outline-secondary" %><center>